/// Hikayelerde gecen kelimelerin ORTAK sozlugu.
///
/// Tek havuz: ayni kelime birden cok hikayede gecerse tekrar yazilmaz.
/// Yuzlerce hikayeye olceklenir.
library;

import '../model/hikaye.dart';

class HikayeSozluk {
  const HikayeSozluk._();

  static const List<SozlukGirdisi> girdiler = <SozlukGirdisi>[
    SozlukGirdisi(kelime: 'wake', okunus: 'veyk', trAnlam: 'uyanmak',
        ornekCumle: 'I wake up at seven.'),
    SozlukGirdisi(kelime: 'kitchen', okunus: 'ki-cin', trAnlam: 'mutfak',
        ornekCumle: 'She is in the kitchen.'),
    SozlukGirdisi(kelime: 'breakfast', okunus: 'brek-fist', trAnlam: 'kahvalti',
        ornekCumle: 'We eat breakfast together.'),
    SozlukGirdisi(kelime: 'garden', okunus: 'gaar-din', trAnlam: 'bahce',
        ornekCumle: 'The garden is small.'),
    SozlukGirdisi(kelime: 'neighbour', okunus: 'ney-bir', trAnlam: 'komsu',
        ornekCumle: 'Our neighbour is kind.'),
    SozlukGirdisi(kelime: 'classroom', okunus: 'klas-rum', trAnlam: 'sinif',
        ornekCumle: 'The classroom is big.'),
    SozlukGirdisi(kelime: 'lesson', okunus: 'le-sin', trAnlam: 'ders',
        ornekCumle: 'The lesson starts at nine.'),
    SozlukGirdisi(kelime: 'nervous', okunus: 'nör-vis', trAnlam: 'gergin',
        ornekCumle: 'He is nervous before the exam.'),
    SozlukGirdisi(kelime: 'station', okunus: 'stey-sin', trAnlam: 'istasyon',
        ornekCumle: 'The station is near.'),
    SozlukGirdisi(kelime: 'ticket', okunus: 'ti-kit', trAnlam: 'bilet',
        ornekCumle: 'I buy a ticket.'),
    SozlukGirdisi(kelime: 'window', okunus: 'vin-dou', trAnlam: 'pencere',
        ornekCumle: 'I open the window.'),
    SozlukGirdisi(kelime: 'market', okunus: 'maar-kit', trAnlam: 'pazar',
        ornekCumle: 'The market is open.'),
    SozlukGirdisi(kelime: 'tomato', okunus: 'to-maa-tou', trAnlam: 'domates',
        ornekCumle: 'I need two tomatoes.'),
    SozlukGirdisi(kelime: 'cheese', okunus: 'ciiz', trAnlam: 'peynir',
        ornekCumle: 'This cheese is fresh.'),
    SozlukGirdisi(kelime: 'office', okunus: 'o-fis', trAnlam: 'ofis',
        ornekCumle: 'She works in an office.'),
    SozlukGirdisi(kelime: 'meeting', okunus: 'mii-ting', trAnlam: 'toplanti',
        ornekCumle: 'The meeting is at ten.'),
    SozlukGirdisi(kelime: 'report', okunus: 'ri-port', trAnlam: 'rapor',
        ornekCumle: 'He writes a report.'),
    SozlukGirdisi(kelime: 'doctor', okunus: 'dok-tir', trAnlam: 'doktor',
        ornekCumle: 'The doctor is busy.'),
    SozlukGirdisi(kelime: 'medicine', okunus: 'med-sin', trAnlam: 'ilac',
        ornekCumle: 'Take this medicine.'),
    SozlukGirdisi(kelime: 'headache', okunus: 'hed-eyk', trAnlam: 'bas agrisi',
        ornekCumle: 'I have a headache.'),
    SozlukGirdisi(kelime: 'guitar', okunus: 'gi-taar', trAnlam: 'gitar',
        ornekCumle: 'She plays the guitar.'),
    SozlukGirdisi(kelime: 'practice', okunus: 'prak-tis', trAnlam: 'alistirma',
        ornekCumle: 'Practice makes perfect.'),
    SozlukGirdisi(kelime: 'song', okunus: 'song', trAnlam: 'sarki',
        ornekCumle: 'This song is beautiful.'),
    SozlukGirdisi(kelime: 'grandmother', okunus: 'grend-ma-dir',
        trAnlam: 'buyukanne', ornekCumle: 'My grandmother cooks well.'),
    SozlukGirdisi(kelime: 'soup', okunus: 'suup', trAnlam: 'corba',
        ornekCumle: 'The soup is hot.'),
    SozlukGirdisi(kelime: 'recipe', okunus: 're-si-pi', trAnlam: 'tarif',
        ornekCumle: 'This is an old recipe.'),
    SozlukGirdisi(kelime: 'rain', okunus: 'reyn', trAnlam: 'yagmur',
        ornekCumle: 'The rain is heavy.'),
    SozlukGirdisi(kelime: 'umbrella', okunus: 'am-brel-la', trAnlam: 'semsiye',
        ornekCumle: 'Take an umbrella.'),
    SozlukGirdisi(kelime: 'library', okunus: 'lay-bri-ri', trAnlam: 'kutuphane',
        ornekCumle: 'The library is quiet.'),
    SozlukGirdisi(kelime: 'bus', okunus: 'bas', trAnlam: 'otobus',
        ornekCumle: 'The bus is late.'),
    SozlukGirdisi(kelime: 'shop', okunus: 'sop', trAnlam: 'dukkan',
        ornekCumle: 'The shop opens early.'),
    SozlukGirdisi(kelime: 'price', okunus: 'prays', trAnlam: 'fiyat',
        ornekCumle: 'The price is good.'),
    SozlukGirdisi(kelime: 'teacher', okunus: 'tii-cir', trAnlam: 'ogretmen',
        ornekCumle: 'The teacher is kind.'),
    SozlukGirdisi(kelime: 'homework', okunus: 'houm-vörk', trAnlam: 'odev',
        ornekCumle: 'I do my homework.'),
    SozlukGirdisi(kelime: 'letter', okunus: 'le-tir', trAnlam: 'mektup',
        ornekCumle: 'She writes a letter.'),
    SozlukGirdisi(kelime: 'suitcase', okunus: 'suut-keys', trAnlam: 'bavul',
        ornekCumle: 'My suitcase is heavy.'),
    SozlukGirdisi(kelime: 'sea', okunus: 'sii', trAnlam: 'deniz',
        ornekCumle: 'The sea is blue.'),
    SozlukGirdisi(kelime: 'afternoon', okunus: 'af-tir-nuun',
        trAnlam: 'ogleden sonra', ornekCumle: 'We meet in the afternoon.'),
    SozlukGirdisi(kelime: 'tired', okunus: 'tayrd', trAnlam: 'yorgun',
        ornekCumle: 'I am very tired.'),
    SozlukGirdisi(kelime: 'clean', okunus: 'kliin', trAnlam: 'temiz',
        ornekCumle: 'The room is clean.'),

    // ---- A2 hikayeleri (H-A2-001..003) ----
    SozlukGirdisi(kelime: 'search', okunus: 'sorc', trAnlam: 'aramak',
        ornekCumle: 'She searched the whole room.'),
    SozlukGirdisi(kelime: 'pocket', okunus: 'po-kit', trAnlam: 'cep',
        ornekCumle: 'The keys were in his pocket.'),
    SozlukGirdisi(kelime: 'drawer', okunus: 'droor', trAnlam: 'cekmece',
        ornekCumle: 'Open the top drawer.'),
    SozlukGirdisi(kelime: 'colleague', okunus: 'ko-liig', trAnlam: 'is arkadasi',
        ornekCumle: 'My colleague helped me.'),
    SozlukGirdisi(kelime: 'entrance', okunus: 'ent-rins', trAnlam: 'giris',
        ornekCumle: 'Wait at the entrance.'),
    SozlukGirdisi(kelime: 'platform', okunus: 'plat-form', trAnlam: 'peron',
        ornekCumle: 'The train is on platform two.'),
    SozlukGirdisi(kelime: 'interview', okunus: 'in-tir-vyu', trAnlam: 'gorusme',
        ornekCumle: 'She has a job interview today.'),
    SozlukGirdisi(kelime: 'engineer', okunus: 'en-ci-nir', trAnlam: 'muhendis',
        ornekCumle: 'He is an engineer.'),
    SozlukGirdisi(kelime: 'bench', okunus: 'benc', trAnlam: 'bank (oturak)',
        ornekCumle: 'We sat on a bench.'),
    SozlukGirdisi(kelime: 'sigh', okunus: 'say', trAnlam: 'ic cekmek',
        ornekCumle: 'He sighed and sat down.'),
    SozlukGirdisi(kelime: 'noise', okunus: 'noyz', trAnlam: 'gurultu',
        ornekCumle: 'There is too much noise.'),
    SozlukGirdisi(kelime: 'complain', okunus: 'kim-pleyn', trAnlam: 'sikayet etmek',
        ornekCumle: 'She did not complain.'),
    SozlukGirdisi(kelime: 'polite', okunus: 'pi-layt', trAnlam: 'kibar',
        ornekCumle: 'He is a polite man.'),
    SozlukGirdisi(kelime: 'practise', okunus: 'prak-tis', trAnlam: 'calismak, pratik yapmak',
        ornekCumle: 'I practise every day.'),
    SozlukGirdisi(kelime: 'solution', okunus: 'si-lu-sin', trAnlam: 'cozum',
        ornekCumle: 'We found a solution.'),
    SozlukGirdisi(kelime: 'disturb', okunus: 'dis-torb', trAnlam: 'rahatsiz etmek',
        ornekCumle: 'Sorry to disturb you.'),
    SozlukGirdisi(kelime: 'exam', okunus: 'ig-zam', trAnlam: 'sinav',
        ornekCumle: 'The exam is in June.'),
    SozlukGirdisi(kelime: 'ticket', okunus: 'ti-kit', trAnlam: 'bilet',
        ornekCumle: 'I bought a ticket.'),
  ];

  static Map<String, SozlukGirdisi> get harita =>
      <String, SozlukGirdisi>{
        for (final SozlukGirdisi g in girdiler) g.kelime.toLowerCase(): g
      };

  static Set<String> get kelimeler =>
      girdiler.map((SozlukGirdisi g) => g.kelime.toLowerCase()).toSet();
}
